# Generated by Django 3.2 on 2021-04-09 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210408_0840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippinAddress',
            new_name='ShippingAddress',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paymentMethodd',
            new_name='paymentMethod',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Order',
            new_name='order',
        ),
    ]
